version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "1337:1337"
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: school_x
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro